{
 "title": "sora",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sora_channel_id",
    "query": "SELECT channel_id FROM sora_connection  ORDER BY timestamp DESC LIMIT 50"
   },
   {
    "name": "sora_connection_id",
    "query": "SELECT connection_id FROM sora_connection WHERE  channel_id='$sora_channel_id' ORDER BY timestamp DESC LIMIT 50"
   },
   {
    "name": "sora_label",
    "query": "SELECT label FROM sora_connection WHERE  channel_id='$sora_channel_id' AND connection_id='$sora_connection_id' ORDER BY timestamp DESC LIMIT 50"
   },
   {
    "name": "sora_node_name",
    "query": "SELECT node_name FROM sora_connection WHERE  channel_id='$sora_channel_id' AND connection_id='$sora_connection_id' AND label='$sora_label' ORDER BY timestamp DESC LIMIT 50"
   },
   {
    "name": "sora_version",
    "query": "SELECT version FROM sora_connection WHERE  channel_id='$sora_channel_id' AND connection_id='$sora_connection_id' AND label='$sora_label' AND node_name='$sora_node_name' ORDER BY timestamp DESC LIMIT 50"
   }
  ]
 },
 "panels": [
  {
   "title": "sora_connection",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  channel_id,\n  session_id,\n  connection_id,\n  client_id,\n  role,\n  version,\n  label,\n  node_name,\n  multistream,\n  simulcast,\n  spotlight,\n  created_at\nFROM sora_connection\nWHERE\n  $__timeFilter(timestamp) AND\n  channel_id = '$sora_channel_id' AND\n  label = '$sora_label' AND\n  node_name = '$sora_node_name' AND\n  version = '$sora_version'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "rtc_codec_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "codec",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  stats_id,\n  mime_type,\n  clock_rate,\n  payload_type,\n  channels\nFROM rtc_codec_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_transport_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "transpor_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  packets_sent,\n  packets_received,\n  bytes_sent,\n  bytes_received,\n  local_certificate_id,\n  tls_version,\n  dtls_cipher,\n  srtp_cipher,\n  selected_candidate_pair_changes\nFROM rtc_transport_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  bytes_received - lag(bytes_received) OVER (ORDER BY \"time\") AS \"bytes_received\",\n  bytes_sent - lag(bytes_sent) OVER (ORDER BY \"time\") AS \"bytes_sent\"\nFROM rtc_transport_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "bytes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  bytes_received - lag(bytes_received) OVER (ORDER BY \"time\") AS \"bytes_received\",\n  bytes_received AS \"bytes_received (total)\",\n  bytes_sent - lag(bytes_sent) OVER (ORDER BY \"time\") AS \"bytes_sent\",\n  bytes_sent AS \"bytes_sent (total)\"\nFROM rtc_transport_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  packets_received - lag(packets_received) OVER (ORDER BY \"time\") AS \"packets_received\",\n  packets_sent - lag(packets_sent) OVER (ORDER BY \"time\") AS \"packets_sent\"\nFROM rtc_transport_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "packets",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  packets_received - lag(packets_received) OVER (ORDER BY \"time\") AS \"packets_received\",\n  packets_received AS \"packets_received (total)\",\n  packets_sent - lag(packets_sent) OVER (ORDER BY \"time\") AS \"packets_sent\",\n  packets_sent AS \"packets_sent (total)\"\nFROM rtc_transport_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_inbound_rtp_stream_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "inbound_rtp_stream_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id,\n  ssrc,\n  kind,\n  codec_id,\n  packets_received,\n  packets_lost,\n  jitter,\n  packets_discarded,\n  packets_repaired,\n  burst_packets_lost,\n  burst_packets_discarded,\n  burst_loss_count,\n  burst_discard_count,\n  burst_loss_rate,\n  burst_discard_rate,\n  gap_loss_rate,\n  gap_discard_rate,\n  frames_dropped,\n  partial_frames_lost,\n  full_frames_lost,\n  remote_id,\n  frames_decoded,\n  key_frames_decoded,\n  frame_width,\n  frame_height,\n  frame_bit_depth,\n  frames_per_second,\n  qp_sum,\n  total_decode_time,\n  total_inter_frame_delay,\n  total_squared_inter_frame_delay,\n  voice_activity_flag,\n  last_packet_received_timestamp,\n  average_rtcp_interval,\n  header_bytes_received,\n  fec_packets_received,\n  fec_packets_discarded,\n  bytes_received,\n  packets_failed_decryption,\n  packets_duplicated,\n  nack_count,\n  fir_count,\n  pli_count,\n  sli_count,\n  total_processing_delay,\n  estimated_playout_timestamp,\n  jitter_buffer_delay,\n  jitter_buffer_emitted_count,\n  total_samples_received,\n  total_samples_decoded,\n  samples_decoded_with_silk,\n  samples_decoded_with_celt,\n  concealed_samples,\n  silent_concealed_samples,\n  concealment_events,\n  inserted_samples_for_deceleration,\n  removed_samples_for_acceleration,\n  audio_level,\n  total_audio_energy,\n  total_samples_duration,\n  frames_received,\n  decoder_implementation\nFROM rtc_inbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  bytes_received - lag(bytes_received) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"bytes_received\"\nFROM rtc_inbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  bytes_received - lag(bytes_received) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"bytes_received\",\n  bytes_received AS \"bytes_received (total)\"\nFROM rtc_inbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  packets_received - lag(packets_received) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"packets_received\"\nFROM rtc_inbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  packets_received - lag(packets_received) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"packets_received\",\n  packets_received AS \"packets_received (total)\"\nFROM rtc_inbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_outbound_rtp_stream_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "outbound_rtp_stream_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id,\n  ssrc,\n  kind,\n  codec_id,\n  packets_sent,\n  bytes_sent,\n  rtx_ssrc,\n  media_source_id,\n  remote_id,\n  last_packet_sent_timestamp,\n  header_bytes_sent,\n  packets_discarded_on_send,\n  bytes_discarded_on_send,\n  fec_packets_sent,\n  retransmitted_packets_sent,\n  retransmitted_bytes_sent,\n  target_bitrate,\n  total_encoded_bytes_target,\n  frame_width,\n  frame_height,\n  frame_bit_depth,\n  frames_per_second,\n  frames_sent,\n  huge_frames_sent,\n  frames_encoded,\n  key_frames_encoded,\n  frames_discarded_on_send,\n  qp_sum,\n  total_samples_sent,\n  samples_encoded_with_silk,\n  samples_encoded_with_celt,\n  voice_activity_flag,\n  total_encode_time,\n  total_packet_send_delay,\n  average_rtcp_interval,\n  quality_limitation_resolution_changes,\n  nack_count,\n  fir_count,\n  pli_count,\n  sli_count,\n  encoder_implementation\nFROM rtc_outbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  bytes_sent - lag(bytes_sent) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"bytes_sent\"\nFROM rtc_outbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  bytes_sent - lag(bytes_sent) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"bytes_sent \",\n  bytes_sent AS \"bytes_sent (total)\"\nFROM rtc_outbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  packets_sent - lag(packets_sent) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"packets_sent\"\nFROM rtc_outbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  packets_sent - lag(packets_sent) OVER (PARTITION BY stats_id ORDER BY \"time\") AS \"packets_sent\",\n  packets_sent AS \"packets_sent (total)\"\nFROM rtc_outbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_video_source_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "video_source_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  width,\n  height,\n  bit_depth,\n  frames,\n  frames_per_second\nFROM rtc_video_source_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "resulution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  width,\n  height\nFROM rtc_video_source_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "resulution",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  width,\n  height\nFROM rtc_video_source_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "fps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  frames_per_second\nFROM rtc_video_source_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "fps",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  frames_per_second,\n  frames\nFROM rtc_video_source_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_audio_source_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "audio_source",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  audio_level,\n  total_audio_energy,\n  total_samples_duration,\n  echo_return_loss,\n  echo_return_loss_enhancement\nFROM rtc_audio_source_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_data_channel_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "data_channel",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label,\n  data_channel_identifier,\n  messages_sent,\n  messages_received,\n  bytes_sent,\n  bytes_received,\n  state\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "messages_received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  messages_received - lag(messages_received) OVER (PARTITION BY label ORDER BY \"time\") AS \"messages_received\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "messages_received",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  messages_received - lag(messages_received) OVER (PARTITION BY label ORDER BY \"time\") AS \"messages_received\",\n  messages_received AS \"messages_received (total)\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "messages_sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  messages_sent - lag(messages_sent) OVER (PARTITION BY label ORDER BY \"time\") AS \"messages_sent\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "messages_sent",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  messages_sent - lag(messages_sent) OVER (PARTITION BY label ORDER BY \"time\") AS \"messages_sent\",\n  messages_sent AS \"messages_sent (total)\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes_received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  bytes_received - lag(bytes_received) OVER (PARTITION BY label ORDER BY \"time\") AS \"bytes_received\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes_received",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  bytes_received - lag(bytes_received) OVER (PARTITION BY label ORDER BY \"time\") AS \"bytes_received\",\n  bytes_received AS \"bytes_received (total)\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes_sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  bytes_sent - lag(bytes_sent) OVER (PARTITION BY label ORDER BY \"time\") AS \"bytes_sent\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes_sent",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  label AS metric,\n  bytes_sent - lag(bytes_sent) OVER (PARTITION BY label ORDER BY \"time\") AS \"bytes_sent\",\n  bytes_sent AS \"bytes_sent (total)\"\nFROM rtc_data_channel_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_ice_candidate_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "ice_candidate_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_type,\n  stats_id,\n  address,\n  port,\n  protocol,\n  candidate_type,\n  priority,\n  url,\n  relay_protocol\nFROM rtc_ice_candidate_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_ice_candidate_pair_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "ice_candidate_pair_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  packets_sent,\n  packets_received,\n  bytes_sent,\n  bytes_received,\n  last_packet_sent_timestamp,\n  last_packet_received_timestamp,\n  first_request_timestamp,\n  last_request_timestamp,\n  last_response_timestamp,\n  total_round_trip_time,\n  current_round_trip_time,\n  available_outgoing_bitrate,\n  available_incoming_bitrate,\n  circuit_breaker_trigger_count,\n  requests_received,\n  requests_sent,\n  responses_received,\n  responses_sent,\n  retransmissions_received,\n  retransmissions_sent,\n  consent_requests_sent,\n  consent_expired_timestamp,\n  packets_discarded_on_send,\n  bytes_discarded_on_send,\n  request_bytes_sent,\n  consent_request_bytes_sent,\n  response_bytes_sent\nFROM rtc_ice_candidate_pair_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_remote_inbound_rtp_stream_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "remote_inbound_rtp_stream_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  packets_received,\n  packets_lost,\n  jitter,\n  packets_discarded,\n  packets_repaired,\n  burst_packets_lost,\n  burst_packets_discarded,\n  burst_loss_count,\n  burst_discard_count,\n  burst_loss_rate,\n  burst_discard_rate,\n  gap_loss_rate,\n  gap_discard_rate,\n  frames_dropped,\n  partial_frames_lost,\n  full_frames_lost,\n  round_trip_time,\n  total_round_trip_time,\n  fraction_lost,\n  reports_received,\n  round_trip_time_measurements\nFROM rtc_remote_inbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "rtc_remote_outbound_rtp_stream_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "remote_outbound_rtp_stream_stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  stats_id AS metric,\n  packets_sent,\n  bytes_sent,\n  reports_sent,\n  round_trip_time,\n  total_round_trip_time,\n  round_trip_time_measurements\nFROM rtc_remote_outbound_rtp_stream_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  sora_connection_id = '$sora_connection_id'\nORDER BY 1,2"
      }
     ]
    }
   ]
  }
 ]
}