// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
	"time"
)

const InsertSoraNode = `-- name: InsertSoraNode :exec
INSERT INTO sora_node (
  timestamp,
  label, version, node_name
)
SELECT
  $1,
  $2, $3, $4
WHERE
  NOT EXISTS (
    SELECT label
    FROM sora_node
    WHERE (
      (label = $2) AND
      (node_name = $4) AND
      (version = $3)
    )
)
`

type InsertSoraNodeParams struct {
	Timestamp time.Time `json:"timestamp"`
	Label     string    `json:"label"`
	Version   string    `json:"version"`
	NodeName  string    `json:"node_name"`
}

func (q *Queries) InsertSoraNode(ctx context.Context, arg InsertSoraNodeParams) error {
	_, err := q.db.Exec(ctx, InsertSoraNode,
		arg.Timestamp,
		arg.Label,
		arg.Version,
		arg.NodeName,
	)
	return err
}
