// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
	"time"
)

const InsertSoraConnection = `-- name: InsertSoraConnection :exec
INSERT INTO sora_connection (
  timestamp,
  label, version, node_name,
  multistream, simulcast, spotlight,
  role, channel_id, session_id, client_id, connection_id
)
SELECT
  $1,
  $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $11, $12
WHERE
  NOT EXISTS (
    SELECT channel_id
    FROM sora_connection
    WHERE (
      (channel_id = $9) AND
      (session_id = $10) AND
      (client_id = $11) AND
      (connection_id = $12)
    )
)
`

type InsertSoraConnectionParams struct {
	Timestamp    time.Time `json:"timestamp"`
	Label        string    `json:"label"`
	Version      string    `json:"version"`
	NodeName     string    `json:"node_name"`
	Multistream  bool      `json:"multistream"`
	Simulcast    bool      `json:"simulcast"`
	Spotlight    bool      `json:"spotlight"`
	Role         string    `json:"role"`
	ChannelID    string    `json:"channel_id"`
	SessionID    string    `json:"session_id"`
	ClientID     string    `json:"client_id"`
	ConnectionID string    `json:"connection_id"`
}

func (q *Queries) InsertSoraConnection(ctx context.Context, arg InsertSoraConnectionParams) error {
	_, err := q.db.Exec(ctx, InsertSoraConnection,
		arg.Timestamp,
		arg.Label,
		arg.Version,
		arg.NodeName,
		arg.Multistream,
		arg.Simulcast,
		arg.Spotlight,
		arg.Role,
		arg.ChannelID,
		arg.SessionID,
		arg.ClientID,
		arg.ConnectionID,
	)
	return err
}

const InsertSoraNode = `-- name: InsertSoraNode :exec
INSERT INTO sora_node (
  timestamp,
  label, version, node_name
)
SELECT
  $1,
  $2, $3, $4
WHERE
  NOT EXISTS (
    SELECT label
    FROM sora_node
    WHERE (
      (label = $2) AND
      (node_name = $4) AND
      (version = $3)
    )
)
`

type InsertSoraNodeParams struct {
	Timestamp time.Time `json:"timestamp"`
	Label     string    `json:"label"`
	Version   string    `json:"version"`
	NodeName  string    `json:"node_name"`
}

func (q *Queries) InsertSoraNode(ctx context.Context, arg InsertSoraNodeParams) error {
	_, err := q.db.Exec(ctx, InsertSoraNode,
		arg.Timestamp,
		arg.Label,
		arg.Version,
		arg.NodeName,
	)
	return err
}
