name: Release Build

on:
  push:
    tags:
      - '*'

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'

    - run: go install github.com/tcnksm/ghr@latest

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o dist/kohaku_linux_amd64 cmd/kohaku/main.go
        GOOS=darwin GOARCH=amd64 go build -o dist/kohaku_darwin_amd64 cmd/kohaku/main.go
        GOOS=darwin GOARCH=arm64 go build -o dist/kohaku_darwin_arm64 cmd/kohaku/main.go
        gzip dist/*

    - name: Release
      run: |
        ghr -t "${{ secrets.GITHUB_TOKEN }}" -u "${{ github.repository_owner }}" -r "kohaku" --replace "${GITHUB_REF##*/}" dist/
