name: Go Build & Test

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - '*'

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.18"

    - run: go version

    - run: go fmt .

    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2022.1"
        install-go: false

    - name: Test
      run: GIN_MODE=release make test

    - name: Build
      run: make
